version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Comprimiendo funciones para la lambda de consulta..."
      - zip -r function.zip consulta/* -x "consulta/"
  post_build:
    commands:
      - echo "Actualizando función lambda..."
      - aws lambda update-function-code --function-name mylambda --zip-file fileb://function.zip --publish
      - echo "DONE!!"

artifacts:
  files:
    - function.zip